name: outreach
description: OutReachCRM Project

dependencies:
  validate: ^1.6.0
  flutter_launcher_icons: ^0.6.1
  flutter:
    sdk: flutter
  shared_preferences: ^0.4.2
  http: ^0.11.3+16


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  url_launcher: ^3.0.3

  modal_progress_hud: ^0.1.2

flutter_icons:
    image_path: "assets/icon_android.png"
    android: true
    ios: true



dev_dependencies:
  flutter_test:
    sdk: flutter



# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/OutreachCRM_vert_logo.jpg
    - assets/images/OutreachCRM_vert_logo.png
    - assets/images/background-image.png
    - assets/images/login-background.jpg
    - assets/images/icon_android.png
    - assets/images/icon_ios.png


  fonts:
    - family: Signika
      fonts:
        - asset: assets/fonts/Signika-Light.ttf
        - asset: assets/fonts/Signika-Regular.ttf
        - asset: assets/fonts/Signika-SemiBold.ttf
        - asset: assets/fonts/Signika-Bold.ttf




  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages